### PR TITLE
Fix `FromString` nil dereference

### LINKED ISSUE #11: Nil dereference
It dereferences a `nil` pointer here:
https://github.com/stasundr/decimal/blob/00b3eb3f2f5e78da26428dbc467d33b8b18fd5ae/decimal.go#L319-L321

### PR DESCRIPTION
**Pull request by jilio**
Closes #11

### CODE REVIEW

File: decimal_test.go [hunk 1]
```diff
@@ -686,3 +686,19 @@ func TestDecimal_Eq(t *testing.T) {
...
+	ok := d.FromString("123.45")
+
+	if ok {
+		t.Errorf("FromString should not be ok when called on a nil receiver")
+	}
+
+	// Проверка, что после вызова FromString d по-прежнему равно nil
+	if d != nil {
+		t.Errorf("Expected d to remain nil, but it was not nil")
+	}
```
Comment (HarmlessEvil) [inline decimal_test.go:703]: It will always be `nil`, you can't affect it from inside of such method

**Review by HarmlessEvil — APPROVED** [review]
